---
- name: Install Xdummy package
  yum: 
    name:
      - xorg-x11-drv-dummy # Used to allow tests that require GUI
    state: latest
    use_backend: yum
  become: yes

- include_tasks:
  file: xdummy_setup.yml
