---
- name: Install Xdummy package
  yum:
    name:
      - xorg-x11-drv-dummy # Used to allow tests that require GUI
    state: present
    use_backend: yum
  become: true

- include_tasks:
    file: xdummy_setup.yml
