---
- name: Install Xdummy package
  ansible.builtin.package:
    name:
      - xorg-x11-drv-dummy # Used to allow tests that require GUI
    state: present
    enable_plugin: crb
  become: true

- name: Configure Xdummy
  ansible.builtin.include_tasks:
    file: xdummy_setup.yml
