---
- name: Copy Xdummy systemd unit
  ansible.builtin.copy:
    src: "{{ role_path }}/files/xdummy.service"
    dest: "/etc/systemd/system/xdummy.service"
    owner: root
    group: root
    mode: 0644
  notify: "Reload systemd units"
  become: true

- name: Write the Xdummy xorg.conf file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/xorg.conf"
    dest: "/etc/X11/xdummy_xorg.conf"
    owner: root
    group: root
    mode: 0644
  notify: "Start Xdummy service"
  become: true
