---
- name: Write the Xdummy xorg.conf file
  copy:
    src: "{{ role_path }}/files/xorg.conf"
    dest: "/etc/X11/xdummy_xorg.conf"
    owner: root
    group: root
    mode: 0644
  register: xorg_file
  become: yes

- name: Copy Xdummy systemd unit
  copy:
    src: "{{ role_path }}/files/xdummy.service"
    dest: "/etc/systemd/system/xdummy.service"
    owner: root
    group: root
    mode: 0644
  register: xdummy_unit
  become: yes

- name: Reload systemd units
  systemd:
    daemon_reload: yes
  when: xdummy_unit.changed
  become: yes

- name: Start Xdummy service
  service:
    name: xdummy
    enabled: yes
    state: started
  become: yes

- name: Start Xdummy service
  service:
    name: xdummy
    enabled: yes
    state: restarted
  become: yes
  when: xorg_file.changed
  