---
- name: Reload systemd units
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Start Xdummy service
  ansible.builtin.service:
    name: xdummy
    enabled: yes
    state: restarted
  become: true
